version: '4'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234  
      POSTGRES_DB: checking_connections
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
      - /host/path/to/ntx64_odbc_cli/clidriver/bin:/container/path/to/ntx64_odbc_cli/clidriver/bin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  postgres_data:
