db2_to_mssql_mapping = {
    "BIGINT": "BIGINT",
    "BLOB": "VARBINARY(256)",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "CHARACTER": lambda size, precision, scale: f"CHAR({size})",
    "CHAR FOR BIT DATA": lambda size, precision, scale: f"BINARY({size})",
    "CHARACTER VARYING": lambda size, precision, scale: f"VARCHAR({size})",
    "CLOB": "VARCHAR(MAX)",
    "DATE": "DATE",
    "DBCLOB": "NVARCHAR(MAX)",
    "VARBINARY": lambda size, precision, scale: f"VARBINARY({size})",
    "DECIMAL": lambda size, precision, scale: f"DECIMAL({size}, {scale})",
    "SMALLDECIMAL": lambda size, precision, scale: f"DECIMAL({size}, {scale})",
    "NUMERIC": lambda size, precision, scale: f"DECIMAL({size}, {scale})",
    "DECFLOAT": "FLOAT",
    "DOUBLE PRECISION": "FLOAT",
    "DOUBLE": "FLOAT",
    "FLOAT": "FLOAT",
    "DATETIME": "DATETIME2",
    "INTEGER": "INT",
    "INT": "INT",
    "LONG VARCHAR": "VARCHAR(4000)",
    "NCHAR": lambda size, precision, scale: f"NCHAR({size})",
    "NCHAR VARYING": lambda size, precision, scale: f"NVARCHAR({size})",
    "NCLOB": "NVARCHAR(MAX)",
    "NVARCHAR": lambda size, precision, scale: f"NVARCHAR({size})",
    "REAL": "REAL",
    "SMALLINT": "SMALLINT",
    "TIME": "TIME",
    "TIMESTAMP": "DATETIME2",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "VARCHAR FOR BIT DATA": lambda size, precision, scale: f"VARBINARY({size})",
    "VARGRAPHIC": lambda size, precision, scale: f"NVARCHAR({size})",
    "GRAPHIC": lambda size, precision, scale: f"NCHAR({size})",
    "XML": "XML",
}

db2_to_oracle_mapping = {
    "SMALLINT": "NUMBER(6)",
    "INTEGER": "NUMBER(11)",
    "BIGINT": "NUMBER(19)",
    "DECIMAL": lambda size, precision, scale: f"NUMBER({size}, {scale})",
    "NUMERIC": lambda size, precision, scale: f"NUMBER({size}, {scale})",
    "SMALLDECIMAL": lambda size, precision, scale: f"NUMBER({size}, {scale})",
    "DECFLOAT": lambda size, precision, scale: f"NUMBER({size}, {scale})",
    "REAL": "BINARY_FLOAT",
    "DOUBLE": "BINARY_DOUBLE",
    "DATETIME": "TIMESTAMP",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "CHARACTER": lambda size, precision, scale: f"CHAR({size})",
    "CHAR FOR BIT DATA": lambda size, precision, scale: f"RAW({size})",
    "VARCHAR FOR BIT DATA": lambda size, precision, scale: f"RAW({size})",
    "GRAPHIC": lambda size, precision, scale: f"NCHAR({size})",
    "VARGRAPHIC": lambda size, precision, scale: f"NVARCHAR2({size})",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR2({size})",
    "CHARACTER VARYING": lambda size, precision, scale: f"VARCHAR2({size})",
    "CHAR VARYING": lambda size, precision, scale: f"VARCHAR2({size})",
    "CLOB": "CLOB",
    "DBCLOB": "CLOB",
    "DATE": "DATE",
    "TIME": "DATE",
    "TIMESTAMP": "TIMESTAMP",
    "BOOLEAN": "BOOLEAN",
    "BLOB": "BLOB",
    "XML": "XMLTYPE"
}

db2_to_mysql_mapping = {
    "BLOB": "LONGBLOB",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "CHARACTER": lambda size, precision, scale: f"CHAR({size})",
    "CHAR FOR BIT DATA": lambda size, precision, scale: f"BINARY({size})",
    "CLOB": "LONGTEXT",
    "DATE": "DATE",
    "TIME": "TIME",
    "TIMESTAMP": "DATETIME",
    "DATETIME": "DATETIME",
    "DECIMAL": lambda size, precision, scale: f"DECIMAL({size}, {scale})",
    "NUMERIC": lambda size, precision, scale: f"DECIMAL({size}, {scale})",
    "SMALLDECIMAL": lambda size, precision, scale: f"DECIMAL({size}, {scale})",
    "DECFLOAT": "FLOAT",
    "DOUBLE": "DOUBLE",
    "REAL": "DOUBLE",
    "SMALLINT": "SMALLINT",
    "INTEGER": "INT",
    "BIGINT": "BIGINT",
    "VARCHAR FOR BIT DATA": lambda size, precision, scale: f"VARBINARY({size})",
    "GRAPHIC": lambda size, precision, scale: f"CHAR({size})",
    "VARGRAPHIC": lambda size, precision, scale: f"VARCHAR({size})",
    "DBCLOB": "LONGTEXT",
    "NCLOB": "LONGTEXT",
    "NVARCHAR": "VARCHAR",
    "XML": "XML",
    "BOOLEAN": "TINYINT(1)",
}
db2_to_postgres_mapping = {
    "BLOB": "BYTEA",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "CHARACTER": lambda size, precision, scale: f"CHAR({size})",
    "CHAR FOR BIT DATA": lambda size, precision, scale: f"BIT({size})",
    "CHARACTER VARYING": lambda size, precision, scale: "TEXT" if size == "MAX" else f"VARCHAR({size})",
    "CLOB": "TEXT",
    "DATE": "DATE",
    "TIME": "TIME",
    "TIMESTAMP": "TIMESTAMP",
    "DATETIME": "TIMESTAMP",
    "DECIMAL": lambda size, precision, scale: f"NUMERIC({size}, {scale})",
    "SMALLDECIMAL": lambda size, precision, scale: f"NUMERIC({size}, {scale})",
    "NUMERIC": lambda size, precision, scale: f"NUMERIC({size}, {scale})",
    "DECFLOAT": "FLOAT",
    "DOUBLE": "DOUBLE PRECISION",
    "REAL": "DOUBLE PRECISION",
    "SMALLINT": "SMALLINT",
    "INTEGER": "INTEGER",
    "BIGINT": "BIGINT",
    "VARCHAR FOR BIT DATA": "BYTEA",
    "GRAPHIC": lambda size, precision, scale: f"CHAR({size})",
    "VARGRAPHIC": lambda size, precision, scale: f"VARCHAR({size})",
    "DBCLOB": "TEXT",
    "NCLOB": "TEXT",
    "NVARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "XML": "XML",
    "BOOLEAN": "BOOLEAN"
}
