# DEVELOP BY Geetanshu/Neha/YOGESH SHARMA
# Update by ANUJ JAin

mssql_to_oracle_mapping = {
    "TINYINT": lambda size, precision, scale: f"NUMBER({precision})",
    "SMALLINT": lambda size, precision, scale: f"NUMBER({precision})",
    "INT": lambda size, precision, scale: f"NUMBER({precision})",
    "BIGINT": lambda size, precision, scale: f"NUMBER({precision})",
    "DECIMAL": lambda size, precision, scale: f"NUMBER({precision},{scale})",
    "NUMERIC": lambda size, precision, scale: f"NUMBER({precision},{scale})",
    "FLOAT": "BINARY_FLOAT",
    "REAL": "BINARY_DOUBLE",
    "DATE": "DATE",
    "TIME": "TIMESTAMP",
    "DATETIME": "DATE",
    "SMALLDATETIME": "TIMESTAMP",
    "DATETIME2": "TIMESTAMP",
    "TIMESTAMP": "TIMESTAMP",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR2({size})",
    "TEXT": "CLOB",
    "BINARY": lambda size, precision, scale: f"RAW({size})",
    "VARBINARY": "BLOB",
    "NCHAR": lambda size, precision, scale: f"NCHAR({size})",
    "NVARCHAR": lambda size, precision, scale: f"NVARCHAR2({size})",
    "NTEXT": "NCLOB",
    "BOOLEAN": lambda size, precision, scale: f"NUMBER(1)",
    "BIT": lambda size, precision, scale: f"NUMBER(1)",
    "UNIQUEIDENTIFIER": "RAW(16)",
    "SMALLMONEY": "FLOAT",
    "XML": "CLOB",
    "IMAGE":"LONG RAW"
}

mssql_to_mysql_mapping = {
    "TINYINT": "TINYINT",
    "SMALLINT": "SMALLINT",
    "INT": "INT",
    "BIGINT": "BIGINT",
    "DECIMAL": lambda size, precision, scale: f"DECIMAL({precision},{scale})",
    "NUMERIC": lambda size, precision, scale: f"DECIMAL({precision},{scale})",
    "FLOAT": "FLOAT",
    "DATETIME2": "DATETIME",
    "REAL": "FLOAT",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "NCHAR": lambda size, precision, scale: f"CHAR({size}) CHARACTER SET utf8mb4",
    "NVARCHAR": lambda size, precision, scale: f"VARCHAR({size}) CHARACTER SET utf8mb4",
    "NTEXT": "LONGTEXT",
    "TEXT": "TEXT",
    "DATETIME": "DATETIME",
    "TIMESTAMP": "TIMESTAMP",
    "SMALLDATETIME": "DATETIME",
    "DATE": "DATE",
    "TIME": "TIME",
    "BINARY": lambda size, precision, scale: f"BINARY({size})",
    "VARBINARY": lambda size, precision, scale: f"VARBINARY({size})",
    "IMAGE": lambda size, precision, scale: f"LONGBLOB({size})",
    "BIT": "TINYINT(1)",
    "BOOLEAN": "TINYINT(1)",
    "UNIQUEIDENTIFIER": lambda size, precision, scale: f"VARCHAR({size})",
    "MONEY": lambda size, precision, scale: f"DECIMAL({precision},{scale})",
    "XML": "LONGTEXT",
}

mssql_to_db2_mapping = {
    "TINYINT": "SMALLINT",
    "SMALLINT": "SMALLINT",
    "INT": "INTEGER",
    "BIGINT": "BIGINT",
    "DECIMAL": lambda size, precision, scale: f"DECIMAL({precision},{scale})",
    "NUMERIC": lambda size, precision, scale: f"DECIMAL({precision},{scale})",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "NCHAR": lambda size, precision, scale: f"NCHAR({size})",
    "NVARCHAR": lambda size, precision, scale: f"NVARCHAR({size})",
    "NTEXT": lambda size, precision, scale: f"DBCLOB({size})",
    "FLOAT": "DOUBLE",
    "REAL": "REAL",
    "TEXT": "CLOB",
    "DATETIME": "TIMESTAMP",
    "SMALLDATETIME": "TIMESTAMP",
    "DATE": "DATE",
    "BINARY": lambda size, precision, scale: f"BINARY({size})",
    "VARBINARY": lambda size, precision, scale: f"VARBINARY({size})",
    "IMAGE": "BLOB",
    "BIT": "BOOLEAN",
    "BOOLEAN": "BOOLEAN",
    "UNIQUEIDENTIFIER": "CHAR(36)",
    "TIME": "TIME",
    "TIMESTAMP": "TIMESTAMP",
    "DATETIME2": "TIMESTAMP",
    "XML": "CLOB",
}
mssql_to_postgres_mapping = {
    "TINYINT": "SMALLINT",
    "INT": "INTEGER",
    "SMALLINT": "SMALLINT",
    "BIGINT": "BIGINT",
    "DECIMAL": lambda size, precision, scale: f"NUMERIC({precision},{scale})",
    "NUMERIC": lambda size, precision, scale: f"NUMERIC({precision},{scale})",
    "FLOAT": "REAL",
    "CHAR": lambda size, precision, scale: f"CHAR({size})",
    "VARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "NCHAR": lambda size, precision, scale: f"CHAR({size})",
    "NVARCHAR": lambda size, precision, scale: f"VARCHAR({size})",
    "IMAGE": lambda size, precision, scale: f"BYTEA({size})",
    "NTEXT": "TEXT",
    "TEXT": "TEXT",
    "DATETIME": "TIMESTAMP",
    "SMALLDATETIME": "TIMESTAMP",
    "DATETIME2": "TIMESTAMP",
    "TIMESTAMP": "TIMESTAMP",
    "DATE": "DATE",
    "TIME": "TIME",
    "BINARY": "BYTEA",
    "VARBINARY": "BYTEA",
    "BIT": "BOOLEAN",
    "BOOLEAN": "BOOLEAN",
    "UNIQUEIDENTIFIER": "UUID",
    "XML": "XML",
    "REAL": "REAL",
}
